routes/web.php
<?php

use App\Library\Upload;
use Illuminate\Support\Facades\Artisan;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localize' ]
],

function() {

    Route::get('/clear-cache', function() {
        $exitCode = Artisan::call('cache:clear');

        $exitCode = Artisan::call('optimize');

        $exitCode = Artisan::call('route:clear');
        $exitCode = Artisan::call('config:cache');
        $exitCode = Artisan::call('view:clear');
        // return what you want
    });
    Route::get('uploads/thumb/{catalog}/{size}/{tt}/{ta}/{tm}/{file}', function ($catalog, $size_str, $tt, $ta, $tm, $file) {
        $size = Config::get('app.image_sizes.' . $size_str);

        if ($size === null) abort(404);

        $original_path = public_path() . "/uploads/$catalog/$tt/$ta/$tm/$file";
        $new_path = public_path() . '/' . Request::path();
        $new_dir = dirname($new_path);

        $img = Image::cache(function ($image) use ($original_path, $size) {
            return $image->make($original_path)->fit($size[0], $size[1]);
        }, 10, true);
        @mkdir($new_dir, 0777, true);
        $catalog = 'thumb/' . $catalog . '/' . $size_str;
        $img->save($new_path);

        return $img->response();
    });

    /* ***********CART */
    Route::get("/get-cart", "CartController@getCart");

    Route::get("/get-cart-count", "CartController@getCount");

    Route::post("/add-cart", "CartController@addCart");

    Route::post("/change-cart", "CartController@changeCart");

    Route::post("/delete-cart-item", "CartController@deleteItem");

    Route::delete("/clear-cart", "CartController@clear");

    Route::get("/cart", "OrderController@getForm");

    Route::get("/full-cart-part", "OrderController@getPartCart");

    Route::get("/checkout-form", "OrderController@getCheckoutForm");

    Route::post("/checkout-add", "OrderController@postForm");

    Route::post("/checkpromo", "OrderController@checkPromo");

    Route::get("/places", "ShopController@getPlaces");

    Route::get("/map", "PageController@getMap");

    Route::post("/map-init", "PageController@postMapInit");

    Route::post("/payment-action", "OrderController@payment");

    Route::get("/menu-shops", "PageController@getShops");

    Route::post("/online-payment", "OrderController@onlinePayment");

    Route::get("/test-file", function(){
        print_r(upload::getThumbMainProductFile("product", 4, "213x157"));
    });

    /* ***********CART */
    // Route::get('/test', function(){
    //     $expiresAt = Carbon\Carbon::now()->addMinutes(10);

    //     Cache::put('key', 'value', $expiresAt);


    //     $value = Illuminate\Support\Facades\Cache::get('key');
    //     var_dump($value);
    // });

    Route::get('/', 'PageController@getIndex')->name('home');

    // Static pages

    Route::get('/dir/{alias}', 'PageController@getDir');
    Route::get('/page/{alias}', 'PageController@show');

    // All Category
    Route::get('/category/all', 'PageController@getAllCategory');
    Route::get('/category/{alias}', 'PageController@getCategory');

//    Route::get('/brand-shops', 'ShopController@getBrandShops')->name('brand-shops');
//    Route::get('/private-shops', 'ShopController@getPrivateShops')->name('private-shops');
    Route::get('/recommended-shops', 'ShopController@getRecommendedShops')->name('recommended_shops');

    Route::get('/feedback', 'PageController@getFeedback');
    Route::post('/feedback', 'PageController@postFeedback');

    // Product
    Route::get('/products', 'ProductController@getIndex');
    Route::get('/product/category/{alias}','ProductController@getCategory');
    Route::get('/product/category2/{alias}','ProductController@getCategory2');
    Route::get('/product/subcategory/{alias}', 'ProductController@SubCategory');
    Route::get('/product/recommended/','ProductController@getRecommended');
    Route::get('/product/discount/','ProductController@getDiscountProducts');
    Route::get('/product/popular', 'ProductController@getPopular');
    Route::get('/product/change-mode/','ProductController@getChangeMode');
    Route::get('/product/form/subcategory', 'ProductController@getSubCategory');

    Route::get('/product/view/{alias}','ProductController@getView');
    Route::get('/product/all/{alias}','ProductController@getAll');
    Route::get('/shop/get/select', 'ShopController@select2Shop');
    Route::get('/shop/number/{id}','ShopController@getPhone');
    Route::get('/shop/view/{alias}','ShopController@show');
    Route::get('/shop/view/change-mode', 'ShopController@getChangeMode');
    Route::get('/shop/product', 'ShopController@product');
    Route::post('/product/{what}/{id}', 'ProductController@likeOrDislike');
    Route::get('/product/add-favourite/{product_id}','ProductController@addFavourite');
    Route::get('/product/like/{product_id}', 'ProductController@postLike');
    Route::post('/comment/insert', 'CommentController@postComment');



    // Product

	Route::group(['middleware' => 'guest'], function(){
		Route::get('/register', 'UserController@getRegister');
		Route::post('/user-register', 'UserController@postUserRegister');
		Route::post('/seller-register', 'UserController@postSellerRegister');
		Route::get('/login', 'UserController@getLogin');
		Route::post('/ajax-login', 'UserController@postAjaxLogin');
		Route::get('/form-confirm-code', 'UserController@postFormConfirmCode');
		Route::post('/resend-code', 'UserController@postResendCode');
		Route::post('/check-code', 'UserController@postVarificate');
	});

	Route::group(['middleware' => ['auth']], function(){
		Route::get('/cabinet', 'UserController@getProfile');
		Route::get('/logout', 'UserController@getLogout');

		// Cabinet
		Route::get('/cabinet/product', 'CabinetController@getIndex');
		Route::get('/cabinet/favorite', 'CabinetController@getFavorite');
		Route::get('/cabinet/shop', 'CabinetController@getShops');
		Route::get('/cabinet/reviews', 'CabinetController@getReviews');
		Route::get('/cabinet/user/reviews', 'CabinetController@getUserReviews');
		Route::get('/cabinet/profile', 'CabinetController@getProfile');
		Route::post('/cabinet/profile', 'CabinetController@postProfile');
		Route::post('/cabinet/password', 'CabinetController@postChangePassword');

		// delete favorite product
		Route::post('cabinet/favorite/delete', 'CabinetController@postDelete');

        // Cabinet Shop
		Route::get('/cabinet/shop', 'ShopController@getForm');
		Route::post('/cabinet/shop', 'ShopController@postForm');

		// Cabinet Product
		Route::get('/cabinet/product/form/{id?}', 'ProductController@getForm');
		Route::post('/cabinet/product/form/{id?}', 'ProductController@postForm');
		Route::post('/cabinet/index/delete', 'ProductController@postDelete');

        Route::post('/cabinet/product/send-file', 'ProductController@uploadFile');
        Route::post('/cabinet/product/remove-file', 'ProductController@removeFile');


		/* ORDER*/
		Route::get("/cabinet/orders",'CabinetController@getOrders');
		Route::get("/cabinet/my-orders",'CabinetController@getMyOrders');
		Route::get("/cabinet/my-order",'CabinetController@getMyOrder');
		Route::post("/cabinet/part-orders",'CabinetController@getOrdersPart');
		Route::post("/cabinet/chage-status",'CabinetController@postStatus');
		Route::get('/cabinet/my-balans', 'CabinetController@getMyBalans');


		Route::get('/click-api', 'ClickController@action');
	});






    // Admin
    Route::group(['prefix' => 'mypanel', 'middleware' => ['admin','role:admin'], 'namespace' => 'Backend'], function() {
        Route::get('/', 'PageController@getDashboard');
        Route::get('/page', 'PageController@getIndex');
        Route::get('/page/form/{id?}', 'PageController@getForm');
        Route::post('/page/form/{id?}', 'PageController@postForm');
        Route::post('/page','PageController@postDelete');


		/*
		|--------------------------------------------------------------------------
		| User Routes
		|--------------------------------------------------------------------------
		*/
        Route::get('/user', 'UserController@getIndex');
        Route::get('/user/form/{id?}', 'UserController@getForm');
        Route::post('/user/form/{id?}', 'UserController@postForm');
        Route::post('/user', 'UserController@postDelete');
        Route::get('/user/data', 'UserController@getData');

		/*
		|--------------------------------------------------------------------------
		| Salesman Routes
		|--------------------------------------------------------------------------
		*/
        Route::get('/salesman', 'SalesmanController@getIndex');
        Route::get('/salesman/form/{id?}', 'SalesmanController@getForm');
        Route::post('/salesman/form/{id?}', 'SalesmanController@postForm');
        Route::post('/salesman', 'SalesmanController@postDelete');
        Route::get('/salesman/data', 'SalesmanController@getData');


		/*
		|--------------------------------------------------------------------------
		| Shop Routes
		|--------------------------------------------------------------------------
		*/
        Route::get('/shops','ShopController@getIndex');
        Route::get('/shop/{id}','ShopController@getShow');
        Route::get('/shops/form/{id?}', 'ShopController@getForm');
        Route::post('/shops/form/{id?}', 'ShopController@postForm');
        Route::post('/shops', 'ShopController@postDelete');
        Route::get('/shops/data', 'ShopController@getData');
        Route::get('/shops/getFind', 'ShopController@getFind');
        Route::post('/shop/status', 'ShopController@postStatus');

			/*

app/Models/Shop.php
<?php

namespace App\Models;
use Log;
use Lang;
use App;
use Upload;

use Illuminate\Database\Eloquent\Model;

class Shop extends Model
{
    protected $guarded = [];
    protected $table = 'shops';
    protected $fillable = [
        'main_image',
        // 'phone_view_amount',
        'title', 'address',
        'user_id', 'alias',
        'mall_id', 'lat', "lng",
        'working_hour_start', 'working_hour_end',
        'mall_type','phone',
        'day1',
        'day2',
        'day3',
        'day4',
        'day5',
        'day6',
        'day7',
    ];

    public function direction(){
        return $this->hasOne('App\Models\MallCategory', 'id', 'mall_type');
    }

    public function mall(){
        return $this->hasOne('App\Models\MallCategory', 'id', 'mall_id');
    }

    public function products(){
        if($this->status == 1){
            return $this->hasMany('App\Models\Product')->where('status', 1);
        }else{
            return $this->hasMany('App\Models\Product');
        }
    }

    public function shopPaymeConfig(){
        return $this->hasOne(ShopPaymeConfig::class, 'shop_id' ,'id');
    }

    public function activeProducts(){
        // return $this->hasMany('App\Models\Product')->where()
    }

    public function getPhoneFormatAttribute(){
        $part1 = substr($this->phone, 0,3);
        $part2 = substr($this->phone, 3,2);
        return '+ '.$part1.' '.$part2. " XXX";
    }

    public function workingDays(){

        $days=['rest' => [], 'work' => []];
        for($i=1; $i<8; $i++){
            if($this->{'day'.$i} == 0){
                $days['rest'][] = Lang::get('main.working_days.day'.$i);
            }else{
                $days['work'][] = Lang::get('main.working_days.day'.$i);
            }
        }

        // Log::info($days);
        return $days;
    }

    public function getStatuses(){
        return [
            [
                'class' => $this->status ? 'btn btn-success status_shop' :'btn btn-danger status_shop',
                "type" => "status",
                'text' => 'Активный'
            ],
            [
                'class' => $this->is_recommended ? 'btn btn-success status_shop' :'btn btn-danger status_shop',
                'type' => 'recommend',
                'text' => 'Рекомендованный'
            ],
        ];
    }


    public static function changeStatus($id, $type){
        $data = ["status" => "status", "recommend" => "is_recommended"];
        if(!($item = $data[$type]))
            return false;

        $shop = Shop::find($id);

        if(!$shop)
            return false;

        $shop->$item = $shop->$item ? "0" : "1";
        $shop->save();

        if($item == "status"){
            static::changeStatusProducts($shop->id, $shop->$item);
        }

        return true;
    }

    public static function changeStatusProducts($shop_id, $status){
        Product::where("shop_id", $shop_id)->update(['status' => $status]);
    }

    public static function addMainImage( $id, $name){

        $name = pathinfo($name, PATHINFO_BASENAME);
        $data["main_image"] = $name;

        $shop = Shop::where("id", $id)->update($data);

        $res = Upload::resize("shop", $id, $name);


    }

    public static function editShopPaymeConfig($shop_id, $config = []){
        $paymeConfig = ShopPaymeConfig::find($shop_id);
        if(!$paymeConfig){
            $paymeConfig = new ShopPaymeConfig;
            $paymeConfig->shop_id = $shop_id;
        }
        $paymeConfig->merchant = $config['merchant'];
        $paymeConfig->save();

    }

}

resources/views/frontend/shop/index.blade.php
@extends('layouts.frontend')

@section('content')

<section class="p-t-nav-sticked">
	<div class="cover" style="background-image: url({{ $page['cover'] }})">
		<div class="cover__text text-center">
			<h1>{{ $page['title'] }}</h1>
		</div>
	</div>
	<div class="p-y-layout">
		<div class="container">
			<div class="row p-b-layout">
				<div class="col-sm-12">
					{{ Form::open(['action' => 'ProductController@getIndex', 'id' => 'search_form', 'method'=>'get']) }}
						<div class="big-o-search big-o-search--rounded search__big-o small-shade">
							
							<input type="text" name="keyword" form="search_form" placeholder="Введите название товара" value="{{ Request::get('q') }}" class="big-o-search__input input input--white js-search-autocomplete">
							
							<button href="#" class="search__btn big-o-search__btn icon-search-main" type="submit" form="search_form"></button>
						
						</div>
					{!! Form::close() !!}
				</div>
			</div>

			<div class="row">
				@foreach($shops as $shop)
				<div class="col-xs-6 col-sm-3 col-lg-2 p-x-0 m-b-20">
					@include('partials.shop')
				</div>
				@endforeach
			</div>
			<div class="text-right">
				{!! $shops->render() !!}
			</div>
		</div>
	</div><!--/.p-layout-->
</section>

@stop

@section('scripts')
<script>
	var autocomplete_data = [
		@foreach(App\Models\Product::orderBy('title', 'asc')->pluck('id','title') as $key=>$value)
				{ value:  '{{ $key }}', data: '{{ $value }}' },
		@endforeach
	]

	var auto_complete = $('.js-search-autocomplete');

	auto_complete.autocomplete({
		lookup: autocomplete_data,
	    appendTo: auto_complete.parent(),
	    forceFixPosition: true,
	    zIndex: 5,
	    maxHeight: 250,
	});
</script>
@stop

resources/views/frontend/shop/show.blade.php
@extends('layouts.frontend')

@section('content')

<link rel="stylesheet" href="/assets/leaflet/leaflet.css" />
<script src="/assets/leaflet/leaflet-src.js"></script>


<section class="shop p-t-nav-sticked">
	<div class="p-y-layout">
		<div class="container">
			<div class="row">
				@include("widgets.breadcrumbs", ["pages" => $pages])
				<!-- Sidebar -->
				<div class="col-md-3">
					<?php $fullname = "/uploads/thumb/shop/200x200/".$shop->id."/".$shop->main_image;?>
						<img src="{{ Upload::hasImage($fullname) ? : '/assets/img/noimage-shop.png'}}" alt="Shop image" class="img-responsive default-radius small-shade ln_center_flex">
					
					<br/>
					<h1 class="title m-t-20">{{ $shop->title }}</h1>
					<p class="m-t-20">
						Колличество товаров - <span class="font-bold">{{ $shop->products->count() }}</span>
					</p>

					<div class="btn-contact small-shade default-radius clearfix m-t-20">
						<div class="btn-contact__phone js-phone">
							{{ $shop->phone_format }}
						</div>

						<button class="btn-contact__phone-expander js-phone-expander">Показать</button>
					</div>
					<div class="m-t-20">
						<span class="font-bold">Адрес:</span><br/>
						{{ $shop->address }}
					</div>
					
					
                    <!-- ========== MAP ========== -->
					<div class="p-y-15">
						<a href="" class="cl-purple">Посмотреть на карте <i class="icon-angle-down"></i></a>
					</div>
					<div id="map_shop" class="js-map default-radius small-shade shop__map" data-lat="{{ $shop->lat }}" data-lng="{{ $shop->lng }}"></div>
                    <!-- ========== MAP ========== -->

					<div class="m-t-20">
						<span class="font-bold">Режим работы: {{ Carbon\Carbon::parse($shop->working_hour_start)->format('H:i') }} - {{ Carbon\Carbon::parse($shop->working_hour_end)->format('H:i')}}</span>

						<div class="row">
							@if($shop->day1)
							<div class="col-xs-6">понедельник</div>
							<div class="col-xs-6">{{ Carbon\Carbon::parse($shop->working_hour_start)->format('H:i') }} - {{ Carbon\Carbon::parse($shop->working_hour_end)->format('H:i')}}</div>
							@else
							<div class="col-xs-6">понедельник</div>
							<div class="col-xs-6">Выходной</div>
							@endif
						</div>
						
						<div class="row">
							@if($shop->day2)
							<div class="col-xs-6">вторник</div>
							<div class="col-xs-6">{{ Carbon\Carbon::parse($shop->working_hour_start)->format('H:i') }} - {{ Carbon\Carbon::parse($shop->working_hour_end)->format('H:i')}}</div>
							@else
							<div class="col-xs-6">вторник</div>
							<div class="col-xs-6">Выходной</div>
							@endif
						</div>

						<div class="row">
							@if($shop->day3)
							<div class="col-xs-6">среда</div>
							<div class="col-xs-6">{{ Carbon\Carbon::parse($shop->working_hour_start)->format('H:i') }} - {{ Carbon\Carbon::parse($shop->working_hour_end)->format('H:i')}}</div>
							@else
							<div class="col-xs-6">среда</div>
							<div class="col-xs-6">Выходной</div>
							@endif
						</div>

						<div class="row">
							@if($shop->day4)
							<div class="col-xs-6">четверг</div>
							<div class="col-xs-6">{{ Carbon\Carbon::parse($shop->working_hour_start)->format('H:i') }} - {{ Carbon\Carbon::parse($shop->working_hour_end)->format('H:i')}}</div>
							@else
							<div class="col-xs-6">четверг</div>
							<div class="col-xs-6">Выходной</div>
							@endif
						</div>

						<div class="row">
							@if($shop->day5)
							<div class="col-xs-6">пятница</div>
							<div class="col-xs-6">{{ Carbon\Carbon::parse($shop->working_hour_start)->format('H:i') }} - {{ Carbon\Carbon::parse($shop->working_hour_end)->format('H:i')}}</div>
							@else
							<div class="col-xs-6">пятница</div>
							<div class="col-xs-6">Выходной</div>
							@endif
						</div>

						<div class="row">
							@if($shop->day6)
							<div class="col-xs-6">суббота</div>
							<div class="col-xs-6">{{ Carbon\Carbon::parse($shop->working_hour_start)->format('H:i') }} - {{ Carbon\Carbon::parse($shop->working_hour_end)->format('H:i')}}</div>
							@else
							<div class="col-xs-6">суббота</div>
							<div class="col-xs-6">Выходной</div>
							@endif
						</div>

						<div class="row">
							@if($shop->day7)
							<div class="col-xs-6">воскресенье</div>
							<div class="col-xs-6">{{ Carbon\Carbon::parse($shop->working_hour_start)->format('H:i') }} - {{ Carbon\Carbon::parse($shop->working_hour_end)->format('H:i')}}</div>
							@else
							<div class="col-xs-6">воскресенье</div>
							<div class="col-xs-6">Выходной</div>
							@endif
						</div>		   
					</div>
				</div>

				<!-- Right content main -->
				<div class="col-md-9">
					
					<div class="row">
						<div class="col-sm-6">
							<h1 class="title title--layout">Товары</h1>
						</div>
						{{-- <div class="col-sm-6 text-right">
							<button class="btn btn--purple btn-square icon-grid m-l-10 js-btn-grid" data-active="{{ (Session::get('product-view-mode')=='grid') ? 'true' : 'false'  }}"></button>
								
							<button class="btn btn--gray btn-square icon-list js-btn-list" data-active="{{ (Session::get('product-view-mode')=='list') ? 'true' : 'false'  }}"></button>
						</div> --}}
					</div>

					<!-- Results all products -->
					<div class="row js-products-ajax-container">
						@forelse($products as $product)
						<div class="col-xs-6 col-sm-4 col-md-3 m-b-5">
							<article class="card m-x-0 m-b-20">
								<div class="card__viewport">
									@if($product->sale_status)
							<span class="sale_product">{{ $product->sale_value }} %</span>
						@endif
									<a class="card__img-cont ln_card__img-cont_2" href="/product/view/{{ $product->alias }}">
										<div class="card__img-cover">
											<i class="icon-eye centered"></i>

											<button class="likes likes--white card__likes">
												<i class="icon-like"></i>
												<span class="likes__amount">{{ $product->likes()->count() }}</span>
											</button>
										</div>

										<img src="{{ (!Upload::hasFiles('product',$product->id)) ? '/assets/img/noimage.png' : Upload::getThumbMainProductFile('product',$product->id,'250x375')[0] }}" alt="Shop image">
									</a> 

									<div class="card__content">
										<a class="card__title" href="#">
											{{-- <strong>
												{{ $product->category->title }}, 
											</strong> --}}
											{{ $product->title }}
										</a>
										
										@if($product->sale_value )
							<div class="card__purpl actual_price">{{ $product->price_format }} {{ Config::get('site.currency')[$product->currency] }}</div>

							<div class="card__purple-text">{{ salePrice($product->price, $product->sale_value) }} {{ Config::get('site.currency')[$product->currency] }}</div>

						@else
							<div class="card__purple-text">{{ $product->price_format }} {{ Config::get('site.currency')[$product->currency] }}</div>

						@endif
									</div>

									</a>
								</div>
							</article>
						</div>
					@empty	
						<div class="col-sm-12">
							<div class="bg-white cl-gray p-y-layout text-center default-radius small-shade">
								<img src="{{ asset('assets/img/icon-bag.svg') }}" alt="" height="100" class="m-b-20"><br/>
								В этом магазине еще нет товаров
							</div>
						</div>
					</div>	
					@endforelse
				    <div class="clearfix"></div>
					<!-- PAGINATION -->
					<div class="text-right">
					    <?php $params = Request::all() ?>
						{{ $products->appends($params)->links() }}
					</div>

				</div>
			</div>
		</div>
	</div><!--/.p-layout-->
</section>
@stop

@section('scripts')
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="{{ asset('assets/js/product-mode-changer.js') }}"></script>
<script>
	var map_shop, 
		marker = null;
	mapInit();
	function mapInit(options = {}){
            position = [
                $("#map_shop").data("lat"),
                $("#map_shop").data("lng"),
            ];

            console.log(position);

            accessToken = "pk.eyJ1IjoibnVybWFub3ZpZyIsImEiOiJjampoemg3YW4ycjVrM3ZudmQ1bWk0bjV5In0.ov5Y46Myp4-nugnYyHzHmw";
            map_shop = L.map('map_shop',{
                center: position,
                zoom: 15
            });

            L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            // attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
             accessToken: accessToken
            }).addTo(map_shop);

            addMarker({coords: position});

    }

	function addMarker(info, clear = true){

        var options = {};

        
        if(info.options){
            if(info.icon){
                var icon = L.icon({
                    iconUrl: info.icon,
                    iconSize: [38, 95], // size of the icon
                });
                options.icon = icon;
            }
        }

        var marker = L.marker(info.coords, options);
        
        if(info.popup){
            marker.bindPopup(info.popup);
        }
        
        marker.addTo(map_shop);
        
        map_shop.addLayer(marker);
    }


  	$('.js-phone-expander').click(function(){
		var button = $(this);
	
		$.ajax({
			url : "/shop/number/" + {{ $shop->id }},
			type : 'GET',
			dataType: 'json',

			success: function(data){
				if(data !== 0){
					button.hide();
					$('.js-phone').html('+ ' + data.phone);
				}
			}
		});
	});

  	// Product Mode changer
	var prod_mod_changer = new ProductModeChanger({
		url: '',
		data:  '',
		btnGrid: $('.js-btn-grid'),
		btnList: $('.js-btn-list'),
		resultContainer: $('.js-products-ajax-container'),
	});
</script>

@stop