routes/web.php
<?php

use App\Library\Upload;
use Illuminate\Support\Facades\Artisan;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localize' ]
],

function() {

    Route::get('/clear-cache', function() {
        $exitCode = Artisan::call('cache:clear');

        $exitCode = Artisan::call('optimize');

        $exitCode = Artisan::call('route:clear');
        $exitCode = Artisan::call('config:cache');
        $exitCode = Artisan::call('view:clear');
        // return what you want
    });
    Route::get('uploads/thumb/{catalog}/{size}/{tt}/{ta}/{tm}/{file}', function ($catalog, $size_str, $tt, $ta, $tm, $file) {
        $size = Config::get('app.image_sizes.' . $size_str);

        if ($size === null) abort(404);

        $original_path = public_path() . "/uploads/$catalog/$tt/$ta/$tm/$file";
        $new_path = public_path() . '/' . Request::path();
        $new_dir = dirname($new_path);

        $img = Image::cache(function ($image) use ($original_path, $size) {
            return $image->make($original_path)->fit($size[0], $size[1]);
        }, 10, true);
        @mkdir($new_dir, 0777, true);
        $catalog = 'thumb/' . $catalog . '/' . $size_str;
        $img->save($new_path);

        return $img->response();
    });

    /* ***********CART */
    Route::get("/get-cart", "CartController@getCart");

    Route::get("/get-cart-count", "CartController@getCount");

    Route::post("/add-cart", "CartController@addCart");

    Route::post("/change-cart", "CartController@changeCart");

    Route::post("/delete-cart-item", "CartController@deleteItem");

    Route::delete("/clear-cart", "CartController@clear");

    Route::get("/cart", "OrderController@getForm");

    Route::get("/full-cart-part", "OrderController@getPartCart");

    Route::get("/checkout-form", "OrderController@getCheckoutForm");

    Route::post("/checkout-add", "OrderController@postForm");

    Route::post("/checkpromo", "OrderController@checkPromo");

    Route::get("/places", "ShopController@getPlaces");

    Route::get("/map", "PageController@getMap");

    Route::post("/map-init", "PageController@postMapInit");

    Route::post("/payment-action", "OrderController@payment");

    Route::get("/menu-shops", "PageController@getShops");

    Route::post("/online-payment", "OrderController@onlinePayment");

    Route::get("/test-file", function(){
        print_r(upload::getThumbMainProductFile("product", 4, "213x157"));
    });

    /* ***********CART */
    // Route::get('/test', function(){
    //     $expiresAt = Carbon\Carbon::now()->addMinutes(10);

    //     Cache::put('key', 'value', $expiresAt);


    //     $value = Illuminate\Support\Facades\Cache::get('key');
    //     var_dump($value);
    // });

    Route::get('/', 'PageController@getIndex')->name('home');

    // Static pages

    Route::get('/dir/{alias}', 'PageController@getDir');
    Route::get('/page/{alias}', 'PageController@show');

    // All Category
    Route::get('/category/all', 'PageController@getAllCategory');
    Route::get('/category/{alias}', 'PageController@getCategory');

//    Route::get('/brand-shops', 'ShopController@getBrandShops')->name('brand-shops');
//    Route::get('/private-shops', 'ShopController@getPrivateShops')->name('private-shops');
    Route::get('/recommended-shops', 'ShopController@getRecommendedShops')->name('recommended_shops');

    Route::get('/feedback', 'PageController@getFeedback');
    Route::post('/feedback', 'PageController@postFeedback');

    // Product
    Route::get('/products', 'ProductController@getIndex');
    Route::get('/product/category/{alias}','ProductController@getCategory');
    Route::get('/product/category2/{alias}','ProductController@getCategory2');
    Route::get('/product/subcategory/{alias}', 'ProductController@SubCategory');
    Route::get('/product/recommended/','ProductController@getRecommended');
    Route::get('/product/discount/','ProductController@getDiscountProducts');
    Route::get('/product/popular', 'ProductController@getPopular');
    Route::get('/product/change-mode/','ProductController@getChangeMode');
    Route::get('/product/form/subcategory', 'ProductController@getSubCategory');

    Route::get('/product/view/{alias}','ProductController@getView');
    Route::get('/product/all/{alias}','ProductController@getAll');
    Route::get('/shop/get/select', 'ShopController@select2Shop');
    Route::get('/shop/number/{id}','ShopController@getPhone');
    Route::get('/shop/view/{alias}','ShopController@show');
    Route::get('/shop/view/change-mode', 'ShopController@getChangeMode');
    Route::get('/shop/product', 'ShopController@product');
    Route::post('/product/{what}/{id}', 'ProductController@likeOrDislike');
    Route::get('/product/add-favourite/{product_id}','ProductController@addFavourite');
    Route::get('/product/like/{product_id}', 'ProductController@postLike');
    Route::post('/comment/insert', 'CommentController@postComment');



    // Product

	Route::group(['middleware' => 'guest'], function(){
		Route::get('/register', 'UserController@getRegister');
		Route::post('/user-register', 'UserController@postUserRegister');
		Route::post('/seller-register', 'UserController@postSellerRegister');
		Route::get('/login', 'UserController@getLogin');
		Route::post('/ajax-login', 'UserController@postAjaxLogin');
		Route::get('/form-confirm-code', 'UserController@postFormConfirmCode');
		Route::post('/resend-code', 'UserController@postResendCode');
		Route::post('/check-code', 'UserController@postVarificate');
	});

	Route::group(['middleware' => ['auth']], function(){
		Route::get('/cabinet', 'UserController@getProfile');
		Route::get('/logout', 'UserController@getLogout');

		// Cabinet
		Route::get('/cabinet/product', 'CabinetController@getIndex');
		Route::get('/cabinet/favorite', 'CabinetController@getFavorite');
		Route::get('/cabinet/shop', 'CabinetController@getShops');
		Route::get('/cabinet/reviews', 'CabinetController@getReviews');
		Route::get('/cabinet/user/reviews', 'CabinetController@getUserReviews');
		Route::get('/cabinet/profile', 'CabinetController@getProfile');
		Route::post('/cabinet/profile', 'CabinetController@postProfile');
		Route::post('/cabinet/password', 'CabinetController@postChangePassword');

		// delete favorite product
		Route::post('cabinet/favorite/delete', 'CabinetController@postDelete');

        // Cabinet Shop
		Route::get('/cabinet/shop', 'ShopController@getForm');
		Route::post('/cabinet/shop', 'ShopController@postForm');

		// Cabinet Product
		Route::get('/cabinet/product/form/{id?}', 'ProductController@getForm');
		Route::post('/cabinet/product/form/{id?}', 'ProductController@postForm');
		Route::post('/cabinet/index/delete', 'ProductController@postDelete');

        Route::post('/cabinet/product/send-file', 'ProductController@uploadFile');
        Route::post('/cabinet/product/remove-file', 'ProductController@removeFile');


		/* ORDER*/
		Route::get("/cabinet/orders",'CabinetController@getOrders');
		Route::get("/cabinet/my-orders",'CabinetController@getMyOrders');
		Route::get("/cabinet/my-order",'CabinetController@getMyOrder');
		Route::post("/cabinet/part-orders",'CabinetController@getOrdersPart');
		Route::post("/cabinet/chage-status",'CabinetController@postStatus');
		Route::get('/cabinet/my-balans', 'CabinetController@getMyBalans');


		Route::get('/click-api', 'ClickController@action');
	});






    // Admin
    Route::group(['prefix' => 'mypanel', 'middleware' => ['admin','role:admin'], 'namespace' => 'Backend'], function() {
        Route::get('/', 'PageController@getDashboard');
        Route::get('/page', 'PageController@getIndex');
        Route::get('/page/form/{id?}', 'PageController@getForm');
        Route::post('/page/form/{id?}', 'PageController@postForm');
        Route::post('/page','PageController@postDelete');


		/*
		|--------------------------------------------------------------------------
		| User Routes
		|--------------------------------------------------------------------------
		*/
        Route::get('/user', 'UserController@getIndex');
        Route::get('/user/form/{id?}', 'UserController@getForm');
        Route::post('/user/form/{id?}', 'UserController@postForm');
        Route::post('/user', 'UserController@postDelete');
        Route::get('/user/data', 'UserController@getData');

		/*
		|--------------------------------------------------------------------------
		| Salesman Routes
		|--------------------------------------------------------------------------
		*/
        Route::get('/salesman', 'SalesmanController@getIndex');
        Route::get('/salesman/form/{id?}', 'SalesmanController@getForm');
        Route::post('/salesman/form/{id?}', 'SalesmanController@postForm');
        Route::post('/salesman', 'SalesmanController@postDelete');
        Route::get('/salesman/data', 'SalesmanController@getData');


		/*
		|--------------------------------------------------------------------------
		| Shop Routes
		|--------------------------------------------------------------------------
		*/
        Route::get('/shops','ShopController@getIndex');
        Route::get('/shop/{id}','ShopController@getShow');
        Route::get('/shops/form/{id?}', 'ShopController@getForm');
        Route::post('/shops/form/{id?}', 'ShopController@postForm');
        Route::post('/shops', 'ShopController@postDelete');
        Route::get('/shops/data', 'ShopController@getData');
        Route::get('/shops/getFind', 'ShopController@getFind');
        Route::post('/shop/status', 'ShopController@postStatus');

			/*

app/Models/Page.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App;

class Page extends Model
{
    protected $guarded = [];
    protected $table = 'pages';

    public function getTitleAttribute()
    {
    	return $this->{'title_'.App::getLocale()};
    }

    public function getDescriptionAttribute()
    {
    	return $this->{'description_'.App::getLocale()};
    }
}

app/Http/Controllers/Backend/BannerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Library\Upload;
use App\Models\Banners;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\PromoCode;

use Validator;

use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Lang;
class BannerController extends Controller
{
    //

    public function getIndex(){
        $items = 	Banners::orderBy("id", "desc")->paginate(10);
        return view("backend.banners.index", compact("items"));
    }

    public function getForm($id = null){

        $item = Banners::find($id);

        if(!$item) $item = [];

        return view("backend.banners.form", compact("item"));
    }

    public function postForm(Request $request, $id = null){
        $data = $request->only(['url', 'actived_at']);

        $rules = [
            'url'             => 'required|string',
            'actived_at'          => 'required|date',
        ];

        $validator = Validator::make($data,$rules);

        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput();
        }else{
            if($request->file('img')) {
                $image = $request->file('img');
                $name = time() . '.' . $image->getClientOriginalExtension();
                $destinationPath = public_path('/banners');
                $image->move($destinationPath, $name);
                $data['img'] = time() . '.' . $image->getClientOriginalExtension();

                if($banner = Banners::find($id)){
                    @unlink($destinationPath."/".$banner->img);
                }
            }

            Banners::updateOrCreate(
                ['id' => $id],
                $data
            );

            return redirect()->action('Backend\BannerController@getIndex');
        }
    }

    public function postDelete(Request $request){
        if($request->has('delete') && $promo = Banners::find($request->input('delete'))){
            if($promo->delete()){
                Session::flash('success', Lang::get('alert.success.delete'));
            }

        }

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

// S.Mirakhmedov v.1.1

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Icon;

use Datatables;
use Validator;
use Session;
use Upload;
use Lang;

class CategoryController extends Controller
{
    public function getIndex(){
       	return view('backend.category.index');
    }

    public function getData(){
        return Datatables::eloquent(Category::where('parent_id','0'))->make(true);
    }

    public function postDelete(Request $request){
    	if($request->has('delete') && Category::find($request->input('delete'))->delete()){
    		Session::flash('success', Lang::get('alert.success.delete'));
    	}

    	return redirect()->back();
    }

    public function parentId(Request $request){
        $categories = Category::where('title_ru','like','%'.$request->get('term').'%')
          ->orWhere('title_ru','like','%'.$request->get('term').'%')
            ->get()->toArray();
        return response()->json(['params' => $categories]);
    }


    public function getForm($id = NULL){
        $category = Category::find($id);
        $icons = Icon::all();
        if(!$category) $category = [];
        return view('backend.category.form', compact('category', 'icons'));
    }

    public function postForm(Request $request, $id = NULL){
        
        $data = $request->only('title_ru', 'title_uz','description_ru','description_uz','parent_id', 'icon');

        $rules = [
            'title_ru'       => 'required',
            'title_uz'       => 'required',
        ];

        $validator = Validator::make($data,$rules);

        if($validator->fails()){
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        } else {
              if($id==NULL){
                 $data['parent_id'] = '0';
                 $data['alias'] = $this->aliasCreate($data['title_ru']);
                 $create = Category::create($data);
              } else {
                 unset($data['parent_id']);
                 $category = Category::find($id);
                 if($category) {
                     $category->update($data);
                 }
              }

              if($request->hasFile('image')){
                Upload::saveFile('category', !isset($id) || $id==null ? $create->id : $category->id, $request->file('image'));
              }

              $name = isset($category) ? $category->main_image : null;
                $id = !isset($create) ? $category->id : $create->id;
                $res = Upload::hasMainImage("category", $id, $name);
                
                if($res !== true){
                    Category::addMainImage($id, $res['name']);
                }

              Session::flash('success', Lang::get('alert.success.'.($id==NULL ? 'insert' : 'update')));
              return redirect()->action('Backend\CategoryController@getIndex');  
        }
    }

    public function parentIndex($id){
        $parent = Category::where('parent_id', $id)->get();
        if(!$parent) $parent = [];
        return view('backend.parent.index',compact('parent', 'id'));
    }

    public function addParent(Request $request, $id=null){

        if( $request->isMethod('get') ){
            $category = Category::find($id);;
            $icons = Icon::all();

            return view('backend.category.form', compact('category', 'id', 'icons'));
        }

        // If Request method post ---> do -->

        if($request->isMethod('post')){

            $data=$request->only('title_ru','title_uz','description_ru','description_uz');

            $rules=['title_ru' => 'required'];
            $validate = Validator::make($data,$rules);

            if($validate->fails()){
                return redirect()->back()->withErrors($validate)->withInput();
            }
            // Current ID as a parentId
            $data['parent_id'] = $id;
            $data['alias'] = $this->aliasCreate($data['title_ru']);

            $create = Category::create($data);
                if($create){
                    Session::flash('success', Lang::get('alert.success.'.($id==NULL ? 'insert' : 'update')));
                    return redirect()->action('Backend\CategoryController@parentIndex',[$id]);
                }
        }

    }
    

    private function aliasCreate($value)
    {
        $slug = str_slug($value);
        $model = new Category;
        $slugCount = count($model->whereRaw("alias REGEXP '^{$slug}(-[0-9]+)?$' and id != '{$model->id}'")->get());

        return ($slugCount > 0) ? "{$slug}-{$slugCount}" : $slug;
    }

 
}

app/Http/Controllers/Backend/FileManagerController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FileManagerController extends Controller
{
    public function getIndex()
    {
    	return view('backend.filemanager.index');
    }
}

resources/views/backend/order/index.blade.php
<?php
use App\Models\Order;
use Illuminate\Support\Facades\URL;

?>
@extends('layouts.backend')

@section('content')
<div class="panel panel-default">
    <div class="panel-heading">
        Поиск
    </div>
    
    <div class="panel-body">
      <div class="row">
          {!! Form::open(['method' => 'GET', action('Backend\OrderController@getIndex')]) !!}
          <div class="col-sm-9">
            <div class="form-group">
              <input class="form-control" placeholder="ID заказа" id="search" name="id" type="text">
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <button type="submit" class="btn btn-success btn-block">Найти</button>
            </div>
          </div>
          {!! Form::close() !!}
      </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
          <div class="col-xs-12">
            Заказы
          </div>

        <a class="btn bnt-default" href="{{ URL::to('/mypanel/orders') }}">Все</a> 
        @foreach(Order::status() as $key => $item)
            <a class="btn btn-{{$item['class']}}" href="{{ URL::action('Backend\OrderController@getIndex',['status' => $key]) }}">{{$item['text']}}</a> 
        @endforeach

        <h3>Количество заказов: {{$info->count}}</h3>
        <h3>Общая сумма: {{$info->summ ? : 0}} {{$currency}}</h3>

        </div>
    </div>

    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="data-table"  data-current="{{ URL::full()}}">
              <thead>
                  <tr>
                      <th>ID</th>
                      <th>№ ЗАКАЗА</th>
                      <th>Цена {{$currency}}</th>
                      <th>Время</th>
                      <th>Статус</th>
                      <th>Вид оплаты</th>
                      <th>Статус оплаты</th>

                      <th width="100"></th>
                  </tr>
              </thead>
                  <tbody>
                      @foreach($orders as $key => $order) 
                        <tr>
                            <td>{{ $key+1 }}</td>
                            <td><a href="/mypanel/order/show/{{$order->id}}">№ {{ $order->id }}</a></td>
                            <td>{{ $order->summ }}</td>
                            <td>{{ $order->created_at }}</td>
                            
                            <td>
                            <?php $order_status = Order::status($order->status);?>
                            <span class="text text-{{$order_status['class']}}">{{$order_status['text']}}</span>
                            
                            </td>
                            <td>
                            <?php $pstatus = Order::paytype($order->pay_type);?>
                            <span class="text text-{{$pstatus['class']}}">{{$pstatus['text']}}</span>
                            
                            </td>
                            <td>
                            <?php $pstatus = Order::paystatus($order->pay_status);?>
                            <span class="text text-{{$pstatus['class']}}">{{$pstatus['text']}}</span>
                            
                            </td>
                            

                            <td>                              
                               
                                 <a  name="delete_item" data-toggle="modal" data-target="#deleteModel" class="btn btn-danger" id="{{$order->id}}"  class="btn btn-danger delete_item">
                                  <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                      @endforeach
                  </tbody>       
              </table>
        </div>
        {!! $orders->appends($status !== null ? ['status' => $status] : [])->links() !!}

    </div>
</div>

@stop

@section('scripts')
  @include('partials.backend-delete', ['action' => 'Backend\OrderController@postDelete'])
@stop

resources/views/backend/order/old_\show.blade.php
<?php
use App\Models\OrderProduct;
use App\Models\Order;
?>
@extends('layouts.backend')

@section('content')
<link rel="stylesheet" href="/assets/leaflet/leaflet.css" />
<script src="/assets/leaflet/leaflet-src.js"></script>
<script src="/assets/leaflet/esri-leaflet.js"></script>
<script src="/assets/leaflet/esri-leaflet-geocoder.js"></script>
<div class="panel panel-default">

		<h2>№{{$order->id}}</h2>
</div>
<div class="panel panel-default order"  data-current="{{ URL::full()}}" data-id={{$order->id}}>
	<div class="panel-body">
		
		<h4>Сумма: {{ $order->summ }} сум</h4>
		<h4>Скидка: {{ $order->sale }} сум</h4>
		<h4>Статус: 

		<?php $status = Order::status($order->status);?>
		<span class="text text-{{$status['class']}}">{{$status['text']}}</span>

		</h4>
		<h4>Вид оплаты: 

			<?php $pstatus = Order::paytype($order->pay_type);?>
			<span class="text text-{{$pstatus['class']}}">{{$pstatus['text']}}</span>

		</h4>                  
		<h4>Статус оплаты: 

			<?php $pstatus = Order::paystatus($order->pay_status);?>
			<span class="text text-{{$pstatus['class']}}">{{$pstatus['text']}}</span>

		</h4>
		<h4>Время: {{ $order->created_at }}</h4>
		<h4>Обновлен: {{ $order->updated_at }}</h4>
		<h3>Товары. </h3>
				
		<div class="table-responsive">
			<table class="table table-bordered table-hover" id="data-table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th>Название</th>
						<th>Магазин</th>
						
						<th>Количество</th>
						<th>Скидка</th>
						<th>Сумма</th>
						<th>Статус</th>

					</tr>
				</thead>
				<tbody>
						@foreach($order->products as $key => $or_products) 
						<?php $product = $or_products->product; ?>
						@if(!$product)
							<h2>Некоторые товары из базы были удалены</h2>
						@else

							<tr>
								<td>{{ $key+1 }}</td>
								<td><img style="width: 150px;" src="{{ (Upload::hasFiles('product',$product['id'])) ? Upload::getThumbMainProductFile('product',$product['id'],'208x200')[0] : '/assets/img/noimage.png'}}" alt="Shop image"></td>
								<td>{{ $product->title }} <small>( {{ $product->getSizeInfo($or_products->size_product)}} )</small></td>
								<td>{{ $product->shop->title }}</td>
								<td>{{ $or_products->count }}</td>
								<td>{{ $or_products->count * $or_products->sale }} сум</td>
								<td>{{ $or_products->price * $or_products->count }} сум</td>
								
								<td>
										<?php $status = OrderProduct::status($or_products->status);?>
										<span class="text text-{{$status['class']}}">{{$status['text']}}</span>
								</td>
							</tr>
						@endif
						@endforeach
				</tbody>       
			</table>
		</div>
	</div>
	<div class="col-sm-6">
	@if($order->status == Order::STATUS_INACTIVE)
			<button class="btn btn-danger status" data-status="{{ Order::STATUS_STOPPED}}">Остановить</button>
			<button class="btn btn-info status" data-status="{{ Order::STATUS_STARTED}}">Подготовка товара</button>
	@elseif($order->status == Order::STATUS_STARTED)
			<button class="btn btn-danger status" data-status="{{ Order::STATUS_STOPPED}}">Остановить</button>
			<button class="btn btn-info status" data-status="{{ Order::STATUS_FINISHED}}">Доставлен</button>
	@elseif($order->status == Order::STATUS_FAIL)
			<button class="btn btn-danger status" data-status="{{ Order::STATUS_STOPPED}}">Остановить</button>
			<button class="btn btn-info status" data-status="{{ Order::STATUS_INACTIVE}}">Восстановить</button>
	@endif
	</div>
	<div class="col=sm-6 col-sm-offset-6">
		<?php
		
		 $events = Order::payEvents($order->pay_status);
		
		?>
		@if(!empty($events))
			@foreach($events as $event)
				<span class="{{ $event['class'] }}" data-status="{{$event['status']}}">{{ $event['text'] }}</span>
			@endforeach
		@endif
	</div>
	<div class="clearfix"></div>
</div>

<div class="panel panel-default">
		<h4>Имя: {{$order->username}}</h4>
		<h4>Телефон: {{$order->phone}}</h4>
		<h4>Адрес: {{$order->address}}</h4>
		<h4>Комментария: {{$order->comments}}</h4>
</div>


    {!! Form::hidden('lat', empty($order) ? null : $order->lat, ["class" => "form-control js-lat-input"]) !!}



    {!! Form::hidden('lng', empty($order) ? null : $order->lng, ["class" => "form-control js-lng-input"]) !!}



<div id="order_map" class="js-shop-map only_marker w-100" style="height: 300px; background-color: rgb(204, 204, 204); position: relative; overflow: hidden;">

@stop
@section("scripts")
<script type="text/javascript" src="/assets/js/map.js"></script>
<script>
        var options = {
            addMarker: true,
            // event: {
            //     elem: {
            //         address: $(".address_input"),
            //         lat: $(".js-lat-input"),
            //         lng: $(".js-lng-input"),
            //     },

            // },
            // markers: [
            //             {
            //                 popup: "aaaadasd",
            //                 coords: {
            //                     lat: 41.32661731708665,
            //                     lng: 69.23296451568604
            //                 }
            //             }
            //         ]

        };
        
        

        getSubjects();
        
        function getSubjects(){
        	var id = $(".order").data("id");

        	$.ajax({
        		url: "/mypanel/order/infomap",
        		data: {id: id},
        		success: function(response){
        			markers = [];
        			for(x in response){
        				var marker = {};
        				var popup = "";

        				popup = "<h4>"+response[x].title+"<h4>";
						popup += "<h5>" + response[x].address + "<h5>";
    					popup += "<p>" + response[x].phone + "<p>";

    					if(response[x].type == "user"){
    						marker.icon = 
        						{
        							src: "/assets/img/marker-person.png",
        							width: 55,
        							height: 60
        						};
    					}

        				if(response[x].type == "shop"){
        					
        					marker.icon = 
        						{
        							src: "/assets/img/marker-general.png",
        							width: 55,
        							height: 60
        						};
        					popup += "<p>" + response[x].work_time + "<p>";
        					popup += "<p>" + response[x].work_days + "<p>";
        				}

        				marker.coords = response[x].coords;
        				marker.address = response[x].address;
        				marker.popup = "<div class='popup-map'>" + popup + "</div>";
        				markers.push(marker);

        			}



        			options.markers = markers;

        			console.log(options.markers);
        			if($(".js-lat-input").val() && $(".js-lng-input")){
			            mapInitByPosition("order_map", [$(".js-lat-input").val(), $(".js-lng-input").val()], options) ;
			        }else{
			            mapInitByNavigator("order_map", options);
			        }
        		}
        	})
        }
    </script>
@stop